<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class countrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('countries')->truncate();
        $countries = [
            ['id' => 1, 'iso_code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => 93],
            ['id' => 2, 'iso_code' => 'AL', 'name' => 'Albania', 'phone_code' => 355],
            ['id' => 3, 'iso_code' => 'DZ', 'name' => 'Algeria', 'phone_code' => 213],
            ['id' => 4, 'iso_code' => 'AS', 'name' => 'American Samoa', 'phone_code' => 1684],
            ['id' => 5, 'iso_code' => 'AD', 'name' => 'Andorra', 'phone_code' => 376],
            ['id' => 6, 'iso_code' => 'AO', 'name' => 'Angola', 'phone_code' => 244],
            ['id' => 7, 'iso_code' => 'AI', 'name' => 'Anguilla', 'phone_code' => 1264],
            ['id' => 8, 'iso_code' => 'AQ', 'name' => 'Antarctica', 'phone_code' => 672],
            ['id' => 9, 'iso_code' => 'AG', 'name' => 'Antigua And Barbuda', 'phone_code' => 1268],
            ['id' => 10, 'iso_code' => 'AR', 'name' => 'Argentina', 'phone_code' => 54],
            ['id' => 11, 'iso_code' => 'AM', 'name' => 'Armenia', 'phone_code' => 374],
            ['id' => 12, 'iso_code' => 'AW', 'name' => 'Aruba', 'phone_code' => 297],
            ['id' => 13, 'iso_code' => 'AU', 'name' => 'Australia', 'phone_code' => 61],
            ['id' => 14, 'iso_code' => 'AT', 'name' => 'Austria', 'phone_code' => 43],
            ['id' => 15, 'iso_code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => 994],
            ['id' => 16, 'iso_code' => 'BS', 'name' => 'Bahamas The', 'phone_code' => 1242],
            ['id' => 17, 'iso_code' => 'BH', 'name' => 'Bahrain', 'phone_code' => 973],
            ['id' => 18, 'iso_code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => 880],
            ['id' => 19, 'iso_code' => 'BB', 'name' => 'Barbados', 'phone_code' => 1246],
            ['id' => 20, 'iso_code' => 'BY', 'name' => 'Belarus', 'phone_code' => 375],
            ['id' => 21, 'iso_code' => 'BE', 'name' => 'Belgium', 'phone_code' => 32],
            ['id' => 22, 'iso_code' => 'BZ', 'name' => 'Belize', 'phone_code' => 501],
            ['id' => 23, 'iso_code' => 'BJ', 'name' => 'Benin', 'phone_code' => 229],
            ['id' => 24, 'iso_code' => 'BM', 'name' => 'Bermuda', 'phone_code' => 1441],
            ['id' => 25, 'iso_code' => 'BT', 'name' => 'Bhutan', 'phone_code' => 975],
            ['id' => 26, 'iso_code' => 'BO', 'name' => 'Bolivia', 'phone_code' => 591],
            ['id' => 27, 'iso_code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone_code' => 387],
            ['id' => 28, 'iso_code' => 'BW', 'name' => 'Botswana', 'phone_code' => 267],
            // ['id' => 29, 'iso_code' => 'BV', 'name' => 'Bouvet Island', 'phone_code' => 47],
            ['id' => 30, 'iso_code' => 'BR', 'name' => 'Brazil', 'phone_code' => 55],
            // ['id' => 31, 'iso_code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone_code' => 246],
            ['id' => 32, 'iso_code' => 'BN', 'name' => 'Brunei', 'phone_code' => 673],
            ['id' => 33, 'iso_code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => 359],
            ['id' => 34, 'iso_code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => 226],
            ['id' => 35, 'iso_code' => 'BI', 'name' => 'Burundi', 'phone_code' => 257],
            ['id' => 36, 'iso_code' => 'KH', 'name' => 'Cambodia', 'phone_code' => 855],
            ['id' => 37, 'iso_code' => 'CM', 'name' => 'Cameroon', 'phone_code' => 237],
            ['id' => 38, 'iso_code' => 'CA', 'name' => 'Canada', 'phone_code' => 1],
            ['id' => 39, 'iso_code' => 'CV', 'name' => 'Cape Verde', 'phone_code' => 238],
            ['id' => 40, 'iso_code' => 'KY', 'name' => 'Cayman Islands', 'phone_code' => 1345],
            ['id' => 41, 'iso_code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => 236],
            ['id' => 42, 'iso_code' => 'TD', 'name' => 'Chad', 'phone_code' => 235],
            ['id' => 43, 'iso_code' => 'CL', 'name' => 'Chile', 'phone_code' => 56],
            ['id' => 44, 'iso_code' => 'CN', 'name' => 'China', 'phone_code' => 86],
            ['id' => 45, 'iso_code' => 'CX', 'name' => 'Christmas Island', 'phone_code' => 61],
            ['id' => 46, 'iso_code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone_code' => 672],
            ['id' => 47, 'iso_code' => 'CO', 'name' => 'Colombia', 'phone_code' => 57],
            ['id' => 48, 'iso_code' => 'KM', 'name' => 'Comoros', 'phone_code' => 269],
            ['id' => 49, 'iso_code' => 'CG', 'name' => 'Congo', 'phone_code' => 242],
            ['id' => 50, 'iso_code' => 'CD', 'name' => 'Congo The Democratic Republic Of The', 'phone_code' => 242],
            ['id' => 51, 'iso_code' => 'CK', 'name' => 'Cook Islands', 'phone_code' => 682],
            ['id' => 52, 'iso_code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => 506],
            ['id' => 53, 'iso_code' => 'CI', 'name' => 'Cote D Ivoire (Ivory Coast)', 'phone_code' => 225],
            ['id' => 54, 'iso_code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'phone_code' => 385],
            ['id' => 55, 'iso_code' => 'CU', 'name' => 'Cuba', 'phone_code' => 53],
            ['id' => 56, 'iso_code' => 'CY', 'name' => 'Cyprus', 'phone_code' => 357],
            ['id' => 57, 'iso_code' => 'CZ', 'name' => 'Czech Republic', 'phone_code' => 420],
            ['id' => 58, 'iso_code' => 'DK', 'name' => 'Denmark', 'phone_code' => 45],
            ['id' => 59, 'iso_code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => 253],
            ['id' => 60, 'iso_code' => 'DM', 'name' => 'Dominica', 'phone_code' => 1767],
            ['id' => 61, 'iso_code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => 1809],
            ['id' => 62, 'iso_code' => 'TL', 'name' => 'East Timor', 'phone_code' => 670],
            ['id' => 63, 'iso_code' => 'EC', 'name' => 'Ecuador', 'phone_code' => 593],
            ['id' => 64, 'iso_code' => 'EG', 'name' => 'Egypt', 'phone_code' => 20],
            ['id' => 65, 'iso_code' => 'SV', 'name' => 'El Salvador', 'phone_code' => 503],
            ['id' => 66, 'iso_code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => 240],
            ['id' => 67, 'iso_code' => 'ER', 'name' => 'Eritrea', 'phone_code' => 291],
            ['id' => 68, 'iso_code' => 'EE', 'name' => 'Estonia', 'phone_code' => 372],
            ['id' => 69, 'iso_code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => 251],
            // ['id' => 70, 'iso_code' => 'XA', 'name' => 'External Territories of Australia', 'phone_code' => 61],
            ['id' => 71, 'iso_code' => 'FK', 'name' => 'Falkland Islands', 'phone_code' => 500],
            ['id' => 72, 'iso_code' => 'FO', 'name' => 'Faroe Islands', 'phone_code' => 298],
            ['id' => 73, 'iso_code' => 'FJ', 'name' => 'Fiji Islands', 'phone_code' => 679],
            ['id' => 74, 'iso_code' => 'FI', 'name' => 'Finland', 'phone_code' => 358],
            ['id' => 75, 'iso_code' => 'FR', 'name' => 'France', 'phone_code' => 33],
            // ['id' => 76, 'iso_code' => 'GF', 'name' => 'French Guiana', 'phone_code' => 594],
            ['id' => 77, 'iso_code' => 'PF', 'name' => 'French Polynesia', 'phone_code' => 689],
            ['id' => 78, 'iso_code' => 'TF', 'name' => 'French Southern Territories', 'phone_code' => 33],
            ['id' => 79, 'iso_code' => 'GA', 'name' => 'Gabon', 'phone_code' => 241],
            ['id' => 80, 'iso_code' => 'GM', 'name' => 'Gambia The', 'phone_code' => 220],
            ['id' => 81, 'iso_code' => 'GE', 'name' => 'Georgia', 'phone_code' => 995],
            ['id' => 82, 'iso_code' => 'DE', 'name' => 'Germany', 'phone_code' => 49],
            ['id' => 83, 'iso_code' => 'GH', 'name' => 'Ghana', 'phone_code' => 233],
            ['id' => 84, 'iso_code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => 350],
            ['id' => 85, 'iso_code' => 'GR', 'name' => 'Greece', 'phone_code' => 30],
            ['id' => 86, 'iso_code' => 'GL', 'name' => 'Greenland', 'phone_code' => 299],
            ['id' => 87, 'iso_code' => 'GD', 'name' => 'Grenada', 'phone_code' => 1473],
            // ['id' => 88, 'iso_code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => 590],
            ['id' => 89, 'iso_code' => 'GU', 'name' => 'Guam', 'phone_code' => 1671],
            ['id' => 90, 'iso_code' => 'GT', 'name' => 'Guatemala', 'phone_code' => 502],
            // ['id' => 91, 'iso_code' => 'XU', 'name' => 'Guernsey and Alderney', 'phone_code' => 1481],
            ['id' => 92, 'iso_code' => 'GN', 'name' => 'Guinea', 'phone_code' => 224],
            ['id' => 93, 'iso_code' => 'GW', 'name' => 'Guinea-Bissau', 'phone_code' => 245],
            ['id' => 94, 'iso_code' => 'GY', 'name' => 'Guyana', 'phone_code' => 592],
            ['id' => 95, 'iso_code' => 'HT', 'name' => 'Haiti', 'phone_code' => 509],
            // ['id' => 96, 'iso_code' => 'HM', 'name' => 'Heard and McDonald Islands', 'phone_code' => 61],
            ['id' => 97, 'iso_code' => 'HN', 'name' => 'Honduras', 'phone_code' => 504],
            ['id' => 98, 'iso_code' => 'HK', 'name' => 'Hong Kong S.A.R.', 'phone_code' => 852],
            ['id' => 99, 'iso_code' => 'HU', 'name' => 'Hungary', 'phone_code' => 36],
            ['id' => 100, 'iso_code' => 'IS', 'name' => 'Iceland', 'phone_code' => 354],
            ['id' => 101, 'iso_code' => 'IN', 'name' => 'India', 'phone_code' => 91],
            ['id' => 102, 'iso_code' => 'ID', 'name' => 'Indonesia', 'phone_code' => 62],
            ['id' => 103, 'iso_code' => 'IR', 'name' => 'Iran', 'phone_code' => 98],
            ['id' => 104, 'iso_code' => 'IQ', 'name' => 'Iraq', 'phone_code' => 964],
            ['id' => 105, 'iso_code' => 'IE', 'name' => 'Ireland', 'phone_code' => 353],
            ['id' => 106, 'iso_code' => 'IL', 'name' => 'Israel', 'phone_code' => 972],
            ['id' => 107, 'iso_code' => 'IT', 'name' => 'Italy', 'phone_code' => 39],
            ['id' => 108, 'iso_code' => 'JM', 'name' => 'Jamaica', 'phone_code' => 1876],
            ['id' => 109, 'iso_code' => 'JP', 'name' => 'Japan', 'phone_code' => 81],
            ['id' => 110, 'iso_code' => 'JE', 'name' => 'Jersey', 'phone_code' => 1534],
            ['id' => 111, 'iso_code' => 'JO', 'name' => 'Jordan', 'phone_code' => 962],
            ['id' => 112, 'iso_code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => 7],
            ['id' => 113, 'iso_code' => 'KE', 'name' => 'Kenya', 'phone_code' => 254],
            ['id' => 114, 'iso_code' => 'KI', 'name' => 'Kiribati', 'phone_code' => 686],
            ['id' => 115, 'iso_code' => 'KP', 'name' => 'Korea North', 'phone_code' => 850],
            ['id' => 116, 'iso_code' => 'KR', 'name' => 'Korea South', 'phone_code' => 82],
            ['id' => 117, 'iso_code' => 'KW', 'name' => 'Kuwait', 'phone_code' => 965],
            ['id' => 118, 'iso_code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => 996],
            ['id' => 119, 'iso_code' => 'LA', 'name' => 'Laos', 'phone_code' => 856],
            ['id' => 120, 'iso_code' => 'LV', 'name' => 'Latvia', 'phone_code' => 371],
            ['id' => 121, 'iso_code' => 'LB', 'name' => 'Lebanon', 'phone_code' => 961],
            ['id' => 122, 'iso_code' => 'LS', 'name' => 'Lesotho', 'phone_code' => 266],
            ['id' => 123, 'iso_code' => 'LR', 'name' => 'Liberia', 'phone_code' => 231],
            ['id' => 124, 'iso_code' => 'LY', 'name' => 'Libya', 'phone_code' => 218],
            ['id' => 125, 'iso_code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => 423],
            ['id' => 126, 'iso_code' => 'LT', 'name' => 'Lithuania', 'phone_code' => 370],
            ['id' => 127, 'iso_code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => 352],
            ['id' => 128, 'iso_code' => 'MO', 'name' => 'Macau S.A.R.', 'phone_code' => 853],
            ['id' => 129, 'iso_code' => 'MK', 'name' => 'Macedonia', 'phone_code' => 389],
            ['id' => 130, 'iso_code' => 'MG', 'name' => 'Madagascar', 'phone_code' => 261],
            ['id' => 131, 'iso_code' => 'MW', 'name' => 'Malawi', 'phone_code' => 265],
            ['id' => 132, 'iso_code' => 'MY', 'name' => 'Malaysia', 'phone_code' => 60],
            ['id' => 133, 'iso_code' => 'MV', 'name' => 'Maldives', 'phone_code' => 960],
            ['id' => 134, 'iso_code' => 'ML', 'name' => 'Mali', 'phone_code' => 223],
            ['id' => 135, 'iso_code' => 'MT', 'name' => 'Malta', 'phone_code' => 356],
            // ['id' => 136, 'iso_code' => 'XM', 'name' => 'Man (Isle of)', 'phone_code' => 44],
            ['id' => 137, 'iso_code' => 'MH', 'name' => 'Marshall Islands', 'phone_code' => 692],
            ['id' => 138, 'iso_code' => 'MQ', 'name' => 'Martinique', 'phone_code' => 596],
            ['id' => 139, 'iso_code' => 'MR', 'name' => 'Mauritania', 'phone_code' => 222],
            ['id' => 140, 'iso_code' => 'MU', 'name' => 'Mauritius', 'phone_code' => 230],
            ['id' => 141, 'iso_code' => 'YT', 'name' => 'Mayotte', 'phone_code' => 269],
            ['id' => 142, 'iso_code' => 'MX', 'name' => 'Mexico', 'phone_code' => 52],
            ['id' => 143, 'iso_code' => 'FM', 'name' => 'Micronesia', 'phone_code' => 691],
            ['id' => 144, 'iso_code' => 'MD', 'name' => 'Moldova', 'phone_code' => 373],
            ['id' => 145, 'iso_code' => 'MC', 'name' => 'Monaco', 'phone_code' => 377],
            ['id' => 146, 'iso_code' => 'MN', 'name' => 'Mongolia', 'phone_code' => 976],
            ['id' => 147, 'iso_code' => 'MS', 'name' => 'Montserrat', 'phone_code' => 1664],
            ['id' => 148, 'iso_code' => 'MA', 'name' => 'Morocco', 'phone_code' => 212],
            ['id' => 149, 'iso_code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => 258],
            ['id' => 150, 'iso_code' => 'MM', 'name' => 'Myanmar', 'phone_code' => 95],
            ['id' => 151, 'iso_code' => 'NA', 'name' => 'Namibia', 'phone_code' => 264],
            ['id' => 152, 'iso_code' => 'NR', 'name' => 'Nauru', 'phone_code' => 674],
            ['id' => 153, 'iso_code' => 'NP', 'name' => 'Nepal', 'phone_code' => 977],
            ['id' => 154, 'iso_code' => 'AN', 'name' => 'Netherlands Antilles', 'phone_code' => 599],
            ['id' => 155, 'iso_code' => 'NL', 'name' => 'Netherlands The', 'phone_code' => 31],
            ['id' => 156, 'iso_code' => 'NC', 'name' => 'New Caledonia', 'phone_code' => 687],
            ['id' => 157, 'iso_code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => 64],
            ['id' => 158, 'iso_code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => 505],
            ['id' => 159, 'iso_code' => 'NE', 'name' => 'Niger', 'phone_code' => 227],
            ['id' => 160, 'iso_code' => 'NG', 'name' => 'Nigeria', 'phone_code' => 234],
            ['id' => 161, 'iso_code' => 'NU', 'name' => 'Niue', 'phone_code' => 683],
            ['id' => 162, 'iso_code' => 'NF', 'name' => 'Norfolk Island', 'phone_code' => 672],
            ['id' => 163, 'iso_code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone_code' => 1670],
            ['id' => 164, 'iso_code' => 'NO', 'name' => 'Norway', 'phone_code' => 47],
            ['id' => 165, 'iso_code' => 'OM', 'name' => 'Oman', 'phone_code' => 968],
            ['id' => 166, 'iso_code' => 'PK', 'name' => 'Pakistan', 'phone_code' => 92],
            ['id' => 167, 'iso_code' => 'PW', 'name' => 'Palau', 'phone_code' => 680],
            ['id' => 168, 'iso_code' => 'PS', 'name' => 'Palestinian Territory Occupied', 'phone_code' => 970],
            ['id' => 169, 'iso_code' => 'PA', 'name' => 'Panama', 'phone_code' => 507],
            ['id' => 170, 'iso_code' => 'PG', 'name' => 'Papua new Guinea', 'phone_code' => 675],
            ['id' => 171, 'iso_code' => 'PY', 'name' => 'Paraguay', 'phone_code' => 595],
            ['id' => 172, 'iso_code' => 'PE', 'name' => 'Peru', 'phone_code' => 51],
            ['id' => 173, 'iso_code' => 'PH', 'name' => 'Philippines', 'phone_code' => 63],
            ['id' => 174, 'iso_code' => 'PN', 'name' => 'Pitcairn Island', 'phone_code' => 64],
            ['id' => 175, 'iso_code' => 'PL', 'name' => 'Poland', 'phone_code' => 48],
            ['id' => 176, 'iso_code' => 'PT', 'name' => 'Portugal', 'phone_code' => 351],
            ['id' => 177, 'iso_code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => 1787],
            ['id' => 178, 'iso_code' => 'QA', 'name' => 'Qatar', 'phone_code' => 974],
            ['id' => 179, 'iso_code' => 'RE', 'name' => 'Reunion', 'phone_code' => 262],
            ['id' => 180, 'iso_code' => 'RO', 'name' => 'Romania', 'phone_code' => 40],
            ['id' => 181, 'iso_code' => 'RU', 'name' => 'Russia', 'phone_code' => 7],
            ['id' => 182, 'iso_code' => 'RW', 'name' => 'Rwanda', 'phone_code' => 250],
            ['id' => 183, 'iso_code' => 'SH', 'name' => 'Saint Helena', 'phone_code' => 290],
            ['id' => 184, 'iso_code' => 'KN', 'name' => 'Saint Kitts And Nevis', 'phone_code' => 1869],
            ['id' => 185, 'iso_code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => 1758],
            // ['id' => 186, 'iso_code' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'phone_code' => 508],
            ['id' => 187, 'iso_code' => 'VC', 'name' => 'Saint Vincent And The Grenadines', 'phone_code' => 1784],
            ['id' => 188, 'iso_code' => 'WS', 'name' => 'Samoa', 'phone_code' => 684],
            ['id' => 189, 'iso_code' => 'SM', 'name' => 'San Marino', 'phone_code' => 378],
            ['id' => 190, 'iso_code' => 'ST', 'name' => 'Sao Tome and Principe', 'phone_code' => 239],
            ['id' => 191, 'iso_code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => 966],
            ['id' => 192, 'iso_code' => 'SN', 'name' => 'Senegal', 'phone_code' => 221],
            ['id' => 193, 'iso_code' => 'RS', 'name' => 'Serbia', 'phone_code' => 381],
            ['id' => 194, 'iso_code' => 'SC', 'name' => 'Seychelles', 'phone_code' => 248],
            ['id' => 195, 'iso_code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => 232],
            ['id' => 196, 'iso_code' => 'SG', 'name' => 'Singapore', 'phone_code' => 65],
            ['id' => 197, 'iso_code' => 'SK', 'name' => 'Slovakia', 'phone_code' => 421],
            ['id' => 198, 'iso_code' => 'SI', 'name' => 'Slovenia', 'phone_code' => 386],
            // ['id' => 199, 'iso_code' => 'XG', 'name' => 'Smaller Territories of the UK', 'phone_code' => 44],
            ['id' => 200, 'iso_code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => 677],
            ['id' => 201, 'iso_code' => 'SO', 'name' => 'Somalia', 'phone_code' => 252],
            ['id' => 202, 'iso_code' => 'ZA', 'name' => 'South Africa', 'phone_code' => 27],
            ['id' => 203, 'iso_code' => 'GS', 'name' => 'South Georgia', 'phone_code' => 500],
            ['id' => 204, 'iso_code' => 'SS', 'name' => 'South Sudan', 'phone_code' => 211],
            ['id' => 205, 'iso_code' => 'ES', 'name' => 'Spain', 'phone_code' => 34],
            ['id' => 206, 'iso_code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => 94],
            ['id' => 207, 'iso_code' => 'SD', 'name' => 'Sudan', 'phone_code' => 249],
            ['id' => 208, 'iso_code' => 'SR', 'name' => 'Suriname', 'phone_code' => 597],
            // ['id' => 209, 'iso_code' => 'SJ', 'name' => 'Svalbard And Jan Mayen Islands', 'phone_code' => 47],
            ['id' => 210, 'iso_code' => 'SZ', 'name' => 'Swaziland', 'phone_code' => 268],
            ['id' => 211, 'iso_code' => 'SE', 'name' => 'Sweden', 'phone_code' => 46],
            ['id' => 212, 'iso_code' => 'CH', 'name' => 'Switzerland', 'phone_code' => 41],
            ['id' => 213, 'iso_code' => 'SY', 'name' => 'Syria', 'phone_code' => 963],
            ['id' => 214, 'iso_code' => 'TW', 'name' => 'Taiwan', 'phone_code' => 886],
            ['id' => 215, 'iso_code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => 992],
            ['id' => 216, 'iso_code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => 255],
            ['id' => 217, 'iso_code' => 'TH', 'name' => 'Thailand', 'phone_code' => 66],
            ['id' => 218, 'iso_code' => 'TG', 'name' => 'Togo', 'phone_code' => 228],
            ['id' => 219, 'iso_code' => 'TK', 'name' => 'Tokelau', 'phone_code' => 690],
            ['id' => 220, 'iso_code' => 'TO', 'name' => 'Tonga', 'phone_code' => 676],
            ['id' => 221, 'iso_code' => 'TT', 'name' => 'Trinidad And Tobago', 'phone_code' => 1868],
            ['id' => 222, 'iso_code' => 'TN', 'name' => 'Tunisia', 'phone_code' => 216],
            ['id' => 223, 'iso_code' => 'TR', 'name' => 'Turkey', 'phone_code' => 90],
            ['id' => 224, 'iso_code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => 7370],
            ['id' => 225, 'iso_code' => 'TC', 'name' => 'Turks And Caicos Islands', 'phone_code' => 1649],
            ['id' => 226, 'iso_code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => 688],
            ['id' => 227, 'iso_code' => 'UG', 'name' => 'Uganda', 'phone_code' => 256],
            ['id' => 228, 'iso_code' => 'UA', 'name' => 'Ukraine', 'phone_code' => 380],
            ['id' => 229, 'iso_code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => 971],
            ['id' => 230, 'iso_code' => 'GB', 'name' => 'United Kingdom', 'phone_code' => 44],
            ['id' => 231, 'iso_code' => 'US', 'name' => 'United States', 'phone_code' => 1],
            // ['id' => 232, 'iso_code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'phone_code' => 1],
            ['id' => 233, 'iso_code' => 'UY', 'name' => 'Uruguay', 'phone_code' => 598],
            ['id' => 234, 'iso_code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => 998],
            ['id' => 235, 'iso_code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => 678],
            ['id' => 236, 'iso_code' => 'VA', 'name' => 'Vatican City State (Holy See)', 'phone_code' => 39],
            ['id' => 237, 'iso_code' => 'VE', 'name' => 'Venezuela', 'phone_code' => 58],
            ['id' => 238, 'iso_code' => 'VN', 'name' => 'Vietnam', 'phone_code' => 84],
            ['id' => 239, 'iso_code' => 'VG', 'name' => 'Virgin Islands (British)', 'phone_code' => 1284],
            ['id' => 240, 'iso_code' => 'VI', 'name' => 'Virgin Islands (US)', 'phone_code' => 1340],
            ['id' => 241, 'iso_code' => 'WF', 'name' => 'Wallis And Futuna Islands', 'phone_code' => 681],
            ['id' => 242, 'iso_code' => 'EH', 'name' => 'Western Sahara', 'phone_code' => 212],
            ['id' => 243, 'iso_code' => 'YE', 'name' => 'Yemen', 'phone_code' => 967],
            // ['id' => 244, 'iso_code' => 'YU', 'name' => 'Yugoslavia', 'phone_code' => 38],
            ['id' => 245, 'iso_code' => 'ZM', 'name' => 'Zambia', 'phone_code' => 260],
            ['id' => 246, 'iso_code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => 263],
        ];
        DB::table('countries')->insert($countries);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
